### PR TITLE
[i18] fix alerts 

### PR DESCRIPTION
**Pull request by panleone**
## Abstract
Another bug fix: Alerts are currently not working on master

### CODE REVIEW

**Review by Duddino — APPROVED** [review]
tACK

**Review by JSKitty — COMMENTED** [review]
Alerts look good now - although I'm noticing some `undefined`s around, possibly from failing to rollback to English/nearest-locale, could we fix this in this PR also? Then i19n should be good.

image

**Review by Duddino — APPROVED** [review]
re-tACK

**Review by JSKitty — APPROVED** [review]
**tACK** e5bbc18f339e020752b82f13b93b017f1d3d483b, I did find more translation bugs, but they are out of scope of this PR, so I'll do another PR to fix these myself. LGTM.

**Pull request merged**
