### PR TITLE
Implement app versioning, changelog & update popup

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

For the longest time, MPW has had no proper versioning system #55 - and it's been detrimental for a few reasons;
- Unclear release or update schedule for the public (negative for PR and marketing).
- The inability to designate 'stable' releases, effectively keeping MPW *always* unstable.
- Inability for users to easily see changes, updates, without looking at GitHub.
- More that we could probably keep coming up with!

This PR implements such a versioning system, similar to [Semantic Versioning](https://semver.org/), and based upon the `package.json` file, but with discretion from the Labs team in designating major releases, rather than being API-based, given MPW is a user-facing application, not a developer library.

A Labs maintainer such as myself will designate releases with exclusive 'Version Bump' PRs, these PRs will bump the version in `package.json` according to the magnitude of the changes since the last bump.

image

The maintainer producing the release will also edit the `changelog.md` file, which acts both as a historical store of changes (in the git tree) while also being processed by MPW in to a user-facing Changelog - this gives the devs minimum release friction, while giving MPW users super-easy access to update information.

image

---

image

### Notes:
- This Pull Request itself may be considered *v1.0.0* of MyPIVXWallet, as designated by the `package.json`, thus a followup bump is not necessary, this is the only exception to the exclusive Version Bump guidance.
- The version popup relies on `localStorage` rather than `IndexedDB` as I did not think it was efficient to store a single tiny string inside it, which has no dependency on network (Mainnet/Testnet).

### CODE REVIEW

**Review by Liquid369 — DISMISSED** [review]
tACK c8bc7d3936a7087ac00779b4c52a0ea3d8bf4c0b
v1.0.0 a longgg time coming.

**Review by Duddino — DISMISSED** [review]
tack

**Comment by JSKitty** [comment]
Conflict resolved + Changelog updated, good for re-ACK cc; @Liquid369 @Duddino

**Review by Liquid369 — APPROVED** [review]
re-ACK 9b74f0aee04ea4ada621124e507891d14ae056b7

Changelog updated appropriately

**Review by Duddino — APPROVED** [review]
re-tACK

**Pull request merged**
