### PR TITLE
Network refactor

### PR DESCRIPTION
**Pull request by panleone**
## Abstract

Hugely simplify the `Network` class and the relation between `Wallet` and `Network`. The main idea behind this refactor is that the `Network` should only perform tasks and return values, without having to know the "state" of the wallet and of the blockchain  (synced, number of blocks, etc...). 
See each commit for the precise diff

---

## Testing

Verify that everything is working as before

### CODE REVIEW

**Review by Duddino — CHANGES_REQUESTED** [review]
Overall good refactor.
There's a bug: if you select a dead explorer, it won't sync properly even after if switches to a working one

**Comment by panleone** [comment]
> Overall good refactor. There's a bug: if you select a dead explorer, it won't sync properly even after if switches to a working one

nice catch, the bug was not introduced in this PR, but I fixed it anyways

**Review by Duddino — DISMISSED** [review]
tACK

**Review by JSKitty — COMMENTED** [review]
Most of my testing has gone perfect - syncing is fine, TXs are fine, Promos are fine.

**One strange edge-case I found**, although unsure if this is related to the PR, is that if a TX fails at a point after the Send dialog closed (delayed explorer response), then MPW shows a "Transaction failed!" notification, the screen darkens as if a dialog was opened, but that makes the entire app unclickable.

Potentially need to ensure no dialogs are re-opened or edited after a TX failure?
image

```
subscribeToNetworkEvents global.js:398
emit events.js:153
sendTransaction network.js:335
```

**Comment by panleone** [comment]
> Most of my testing has gone perfect - syncing is fine, TXs are fine, Promos are fine.
> 
> **One strange edge-case I found**, although unsure if this is related to the PR, is that if a TX fails at a point after the Send dialog closed (delayed explorer response), then MPW shows a "Transaction failed!" notification, the screen darkens as if a dialog was opened, but that makes the entire app unclickable.
> 
> Potentially need to ensure no dialogs are re-opened or edited after a TX failure? image
> 
> ```
> subscribeToNetworkEvents global.js:398
> emit events.js:153
> sendTransaction network.js:335
> ```

hmm I cannot replicate the bug (I tried making txs fail in that part of the code)... Anyways it's likely unrelated to this PR

**Review by Duddino — APPROVED** [review]
tACK

**Review by Luke-Larsen — APPROVED** [review]
tACK https://github.com/PIVX-Labs/MyPIVXWallet/pull/323/commits/51319afe10e93e3cdaf997d4a991a86d71901cd8

**Review by JSKitty — APPROVED** [review]
**tACK** 96fe49554734c0b076890565f1ac2b88eafc16de

Tested various wallets and cases, tons of transactions, PIVX Promos, the majority of tabs and net-related functionality, all seems stable.

**Pull request merged**
