### PR TITLE
Add Tsc lint

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

Add typescript linting. It takes type information from jsdoc comments, or is able to deduce it itself
For instance:
```js
function test(hi) {
	return Number.parseInt(hi);
}
```
Will automatically mark the function as `test(hi: any): number`.
Added `@typescript-eslint/no-floating-promises`, the lint will now catch non awaited promises. If the behavior is intentional, `.then(()=>{})` can be used.

### CODE REVIEW

**Review by JSKitty — CHANGES_REQUESTED** [review]
The changes generally look good - nice cleanup! Only one nit, applying to a comment.

However, on a clean dev build, getting a runtime error!
```
# After switching from Master to #130
npm ci
npm run dev
```

image

**Comment by Duddino** [comment]
I encountered that bug in #121 but forgot about it. If we look at the code (in master) we are importing the wallet first and loading the network after that, it only worked because the wallet code was async and the settings code wasn't (and we weren't awaiting), since the scheduler waits for the tick to finish it would execute after the network and work. This is the reason I added `no-floating-promises`, so we can't have these confusing things that break when you make the function async

**Review by JSKitty — DISMISSED** [review]
**tACK** e0fb36d3e69af77a22a0fa1382439fe2e5d944fc, working now - no errors, the extra hardened typing will certainly help prevent many future MPW bugs, great job!! :purple_heart: :muscle:

**Review by Liquid369 — APPROVED** [review]
tACK 27cf487c42b7259fafcfae5cd69767e23fd09a49

Went through this a few times! I did not really encounter any issue gg LGTM

**Comment by Duddino** [comment]
Closing as stale

**Pull request closed without merging**
