### PR TITLE
New 'Settings' page and indentation fix

### PR DESCRIPTION
**Pull request by BreadJS**
## Abstract

I've changed the design of the 'Settings' page to make it more responsive and have a cleaner UI.

## What does this PR address?
MPW was not really responsive for other devices and lacks a good design (IMO). My intent is to redesign MPW for a better look and also make it as responsive as possible for every device.

## What features or improvements were added?
1. New `Settings` page`
    - Menu on left for navigation and content on the right
    - On mobile the menu is on the top and content on the bottom
2. Other changes
    - Fixed indentation

**Note:** *None of the settings have been changed. In later PRs there will be more menus/settings*

## How does this benefit users?
A better design will lure more users in using MPW. This also applies for making the site more responsive.

## PIVX Address
`DDS5v6mPqUN3rdzkp3268LV7TKjHCZqy8c`

### CODE REVIEW

**Review by JSKitty — APPROVED** [review]
**tACK** a92fce6a0918c75d8d8ce98b1669002bbbe2816c, I ran Prettier and also added a JSDoc to the menu switching function, but otherwise... UI is great at all my tested resolutions!

**Review by Duddino — APPROVED** [review]
tACK great work

**Review by Duddino — APPROVED** [review]
re-tACK

**Review by JSKitty — APPROVED** [review]
**tACK** f5364d41850a89501c8b54f97f91c8fc0344f938, looking sexy, a well needed little cleanup that'll make adding new settings much more intuitive.

**Pull request merged**
