### PR TITLE
Faster wallet synchronization

### PR DESCRIPTION
**Pull request by panleone**
## Abstract
Two commits that will make wallet faster

- First commit: In `getLatestBlocks` download all blocks up to the actual chain tip. We can do this since we  are not relying anymore on blockbook.
- Second commit: Call `getLatestBlocks` right after the initial sync. In this way users will not have to wait for a new event `new-block`  to complete the sync.

---

## Testing

Receive some PIVs from someone and verify that the transactions arrives faster (1 block before) than the current master branch

---

### CODE REVIEW

**Review by JSKitty — DISMISSED** [review]
**tACK** 2ca9609e96843b16629eb92ff6e7bba9a9ec950d but with an improvement suggestion:

The (Shield) Tx is instantly recognised in the next block, however, the UI doesn't instantly reflect this until the next `getblockcount` check, so there is an artificial delay to the UI showing balance changes.

Could you emit the balance/activity updates after post-init-sync `getLatestBlocks`?

**Comment by panleone** [comment]
> **tACK** [2ca9609](https://github.com/PIVX-Labs/MyPIVXWallet/commit/2ca9609e96843b16629eb92ff6e7bba9a9ec950d) but with an improvement suggestion:
> 
> The (Shield) Tx is instantly recognised in the next block, however, the UI doesn't instantly reflect this until the next `getblockcount` check, so there is an artificial delay to the UI showing balance changes.
> 
> Could you emit the balance/activity updates after post-init-sync `getLatestBlocks`?

What events are missing?
```
 // At this point download the last missing blocks in the range (blockCount -5, blockCount]
        await this.getLatestBlocks(blockCount);

        // Update both activities post sync
        getEventEmitter().enableEvent('balance-update');
        getEventEmitter().emit('balance-update');
        getEventEmitter().emit('new-tx')
```

**Comment by JSKitty** [comment]
> > **tACK** [2ca9609](https://github.com/PIVX-Labs/MyPIVXWallet/commit/2ca9609e96843b16629eb92ff6e7bba9a9ec950d) but with an improvement suggestion:
> > The (Shield) Tx is instantly recognised in the next block, however, the UI doesn't instantly reflect this until the next `getblockcount` check, so there is an artificial delay to the UI showing balance changes.
> > Could you emit the balance/activity updates after post-init-sync `getLatestBlocks`?
> 
> What events are missing?
> 
> ```
>  // At this point download the last missing blocks in the range (blockCount -5, blockCount]
>         await this.getLatestBlocks(blockCount);
> 
>         // Update both activities post sync
>         getEventEmitter().enableEvent('balance-update');
>         getEventEmitter().emit('balance-update');
>         getEventEmitter().emit('new-tx')
> ```

That is after initial sync, I'm talking about post-sync Tx fetching (the refresh when the wallet is already fully open and synced). The Tx is synchronised, but the UI will not reflect it until the next block count check.

**Comment by panleone** [comment]
> > > **tACK** [2ca9609](https://github.com/PIVX-Labs/MyPIVXWallet/commit/2ca9609e96843b16629eb92ff6e7bba9a9ec950d) but with an improvement suggestion:
> > > The (Shield) Tx is instantly recognised in the next block, however, the UI doesn't instantly reflect this until the next `getblockcount` check, so there is an artificial delay to the UI showing balance changes.
> > > Could you emit the balance/activity updates after post-init-sync `getLatestBlocks`?
> > 
> > 
> > What events are missing?
> > ```
> >  // At this point download the last missing blocks in the range (blockCount -5, blockCount]
> >         await this.getLatestBlocks(blockCount);
> > 
> >         // Update both activities post sync
> >         getEventEmitter().enableEvent('balance-update');
> >         getEventEmitter().emit('balance-update');
> >         getEventEmitter().emit('new-tx')
> > ```
> 
> That is after initial sync, I'm talking about post-sync Tx fetching (the refresh when the wallet is already fully open and synced). The Tx is synchronised, but the UI will not reflect it until the next block count check.

ok I understood, should be fixed now

**Review by JSKitty — APPROVED** [review]
**tACK** 37a341356da25c968a81fcb2be73bea4e6f740d2

Looks good!

**Pull request merged**
