### PR TITLE
Beautify files for consistent style

### PR DESCRIPTION
**Pull request by Duddino**
Abstract:
As the number of contributors is starting to rise, I think we need to establish a consistent code style, which in the future could be enforced by a CI. For now, I've just used [js-beautify](https://www.npmjs.com/package/js-beautify), which if I'm not mistaken, is also what's used in VSCode, one of the most popular editors, which can be invoked like so:
```js-beautify -s 2 $(find -iname "*.js" -or "*.html") -r``` (although I'm not formatting libraries), or be integrated in a number of text editors/IDE.
Although this style may not be identical to the current one, it does resolve some inconsistencies in style.

### CODE REVIEW

**Comment by JSKitty** [comment]
Perfect! I fully agree and believe it's time we finally get some solid guidelines + styles in place, fortunately we can use GitHub actions quite easily for the purpose of CI and auto-reviews on incoming Pull Requests.

I consider this a kind of 'RFC' as it's probably best we find a general consensus on the best style to use, albeit a trivial decision.

For example, I was planning on moving MPW to the 4-space intent (I purely find it easier to read, but less code density).

And for better code clarity without needing to backtrack/reverse-engineer, I have a habit of prefixing all JS variables with their 'pseudo-type', no longer than 3 letters, for example:
```
DOM Elements:   let domThing
Object/Classes: let cThing
Arrays:         let arrThing
ByteArrays:     let bThing
Numbers:        let nThing
Strings:        let strThing
...
```

... you see my gist, I think this helps devs to 'jump in' to MPW, as well as letting one's brain do the type-safety handling correctly and automatically, alongside any automatic CI's.

Thoughts? @Shangaman @Kyeno @Luke-Larsen

**Comment by Duddino** [comment]
I think we should write a config file for js-beautify, and then a style.md explaining the general style of the project

**Comment by Duddino** [comment]
.jsbeautifyrc should be recognised by js-beautify. For now i've left everything with default options, but we can tweak it further

**Comment by Duddino** [comment]
Closing in favor of #50

**Pull request closed without merging**
