### PR TITLE
Host all files internally

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

This PR removes all external files (i.e. fonts, images) and hosts them internally. Other than making everything faster and more predictable, it is needed in #104 since the stricter cors headers forbid fetching files from external hosts

### CODE REVIEW

**Review by JSKitty — APPROVED** [review]
**tACK** 112d863f0f65b5707d615145ab5ee8130fda1bbb, simple and works, nice to have zero dependency on third-parties for assets now - You beat me to it!

**Review by JSKitty — CHANGES_REQUESTED** [review]
Wait, nope, slightly trigger-happy: Image assets are fine, however I'm noticing **Montserrat** is not being applied to the app.

Compare the [**Fleek**](https://bafybeibas4le5fdwoz2bwaxwuuiyqmnlm6rfe247p4xevweqdc7cggs4gi.on.fleek.co/) build to [**Production**](https://mypivxwallet.org/) by opening both fresh tabs, and switch between them, you'll see a font difference between them.

**Review by JSKitty — APPROVED** [review]
**tACK** 48bcb59b64bdfca5927de77ecfcb442cc91ee9a6, fonts are now matching, images are loading, A-OK!

**Review by Liquid369 — APPROVED** [review]
tACK 48bcb59b64bdfca5927de77ecfcb442cc91ee9a6
Re-tested, built and works fine

**Pull request merged**
