### PR TITLE
Redesign wallet unlock flow

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

This PR massively simplifies the `Action <---> Unlock` flow, instead of simply alerting the user to unlock MPW themselves via a notification, MPW now prompts the user to unlock mid-action, continuing the action upon successful unlock, or cancelling the action upon rejection of the password dialog.

image

Additionally, the password prompt may have custom text to give the user better context, and the prompt system also now auto-focuses on the first input within a prompt (if any is given), removing another unnecessary click.

Overall, this is intended to be a neat UX overhaul that reduces some annoying friction in the wallet UI.

## What does this PR address?
It addresses an issue in which users were getting confused and/or encountering a lot of friction using MPW due to the "View Only" system, this PR removes that friction by making Unlocking a seamless process that does not require interrupting actions or cancelling them in order to unlock.

## What features or improvements were added?
When the wallet is locked and the user attempts an action requiring an unlock: MPW now prompts appropriately mid-action without needing to "back out" the action, open the Dashboard, unlock, and re-visit, which was far too many unnecessary steps.

## How does this benefit users?
It massively simplifies the experience when it comes to Locking/Unlocking a user's wallet, reducing many unnecessary clicks, saving time, and resolving confusion.

### CODE REVIEW

**Review by BreadJS — APPROVED** [review]
This will make it a lot more easy for the users! Good job Kitty!

**Review by Duddino — APPROVED** [review]
Can you run prettier? Other than that tACK

**Review by Liquid369 — APPROVED** [review]
tACK ceb97cda0c7aefb0e03220a8bd46cc684ec6796b
I enjoy the new flow

**Review by Duddino — APPROVED** [review]
tACK

**Pull request merged**
