### PR TITLE
[Wallet] Simplify importWallet flow

### PR DESCRIPTION
**Pull request by panleone**
## Abstract

the function `importWallet` must be called only when the wallet is actually imported/generated i.e. only ONCE in the life cycle of the wallet. In particular the function was previously called also on unlocking and this led to useless complications with useless if conditions

---

## Testing

Verify that unlocking still works as it should

### CODE REVIEW

**Review by Liquid369 — DISMISSED** [review]
tACK e8522e89ae4538fe63764d28dd7704744b8f08dc
Lock/unlock for tx's is fine
Blocks stake/create mn/voting

**Review by Duddino — CHANGES_REQUESTED** [review]
I think we should move some of the functions in `setMasterKey` inside the `if`, so we skip calling the whole import routine (Diff for reference, github doesn't let me make suggestion to lines that remained the same).
```
diff --git a/scripts/wallet.js b/scripts/wallet.js
index bfedb90..a1577b0 100644
--- a/scripts/wallet.js
+++ b/scripts/wallet.js
@@ -190,15 +190,16 @@ export class Wallet {
         if (
             mk?.getKeyToExport(nAccount) !==
             this.#masterKey?.getKeyToExport(this.#nAccount)
-        )
+        ) {
             this.reset();
+	    // If this is the global wallet update the network master key
+            if (this.#isMainWallet) {
+		getNetwork().setWallet(this);
+            }
+            for (let i = 0; i < Wallet.chains; i++) this.loadAddresses(i);
+	}
         this.#masterKey = mk;
         this.#nAccount = nAccount;
-        // If this is the global wallet update the network master key
-        if (this.#isMainWallet) {
-            getNetwork().setWallet(this);
-        }
-        for (let i = 0; i < Wallet.chains; i++) this.loadAddresses(i);
     }
 
     /**
```
Also: Can you add some alerts when locking/unlocking the wallet? I know it's not this PR fault, but since we're already touching the logic...

**Review by Duddino — APPROVED** [review]
tACK

**Review by Liquid369 — APPROVED** [review]
re-tACK eb61e8a92e8b73aa27253c58ddb601482734cc4e
I agree with the suggested changes gg

**Pull request merged**
