### PR TITLE
Add Balance Breakdown

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

Due to the natural complexity of PIVX's unit, a user can have MANY balances, it can get pretty confusing, even further for noobs: Public, Shield, Cold Staking, Locked in Masternodes, etc...

This PR hopes to clarity balances better with the addition of a colourcoded breakdown "doughnut" chart, which can be activated upon clicking the Balance on the Dashboard.

image

This PR introduces Chart.js, which in future PRs, will also be used for "Reward History" and "Balance History" charts, as well as other necessary charts to improve UX around the board.

There's also a minor fix to `isMasternodeUTXO`, which allows it to be used on a wallet without a Masternode, where it'll just return "false" rather than error.

## What does this PR address?
It simplifies the vast "multi-balance" system of MPW by letting the user see a full overview of all their balances in their appropriate states, on a single chart.

## What features or improvements were added?
A "Wallet Breakdown", visible apon clicking the Dashboard's Balance.

## How does this benefit users?
An improved UX through allowing the user to see a full breakdown of all of their segregated balance states in a single page and chart - some users get confused when their Masternode collateral is removed from the "Available", this chart clarifies such case better.

### CODE REVIEW

**Review by Duddino — COMMENTED** [review]
To me, it seems a bit like a hidden feature, there is not button or anything

**Comment by shrnkld** [comment]
> To me, it seems a bit like a hidden feature, there is not button or anything

Agreed. You can click on the balance, but also it can be added to the wallet sub menu, poss first in the list.

**Review by Liquid369 — APPROVED** [review]
tACK a33b4e1cb9c6898fb991aeae2622abec6a1e74f9

This is a nice addition/improvement/upgrade, it works well in Safari for Mac users so that is an absolute plus. I hear the guys on it feeling hidden, but the addition into the ... does not really make it any more visible. As of now, I think it's fine as is, and we can discuss visibility at another time. In turn this may be the best spot idk but LGTM

**Review by Duddino — APPROVED** [review]
tACK

**Review by Liquid369 — APPROVED** [review]
tACK be811b26620a0560636e7def801f0b328c5b20c7
+ sign works, looks fine LGTM

**Comment by JSKitty** [comment]
Merging as-is! Need to continue towards Shield.

**Pull request merged**
