### PR TITLE
Fix BIP44 account gap limit

### PR DESCRIPTION
**Pull request by floki008**
i'm Valerio Laera i tested the code with internal ssd cpu  AMD 7 5800x ubuntu operative system.  
I resolved a numerical bug of bip 32 the full documentation can be found at :
https://github.com/EvercodeLab/blockbook/blob/cf65d758724edb3e7fbd3f417cadb0851630789f/api/xpub.go#L16
i changed the number of addresses from 10 to 20 and added indentetion

### CODE REVIEW

**Comment by JSKitty** [comment]
Hey Valerio!

:purple_heart: Thanks for your PR, a reward has been attached for post-merge, I've made some adjustments as the title was a little overkill, although the PR seems valid, as it seems indeed that the [**BIP44 Spec**](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Address_gap_limit) (not BIP32) allows a standard xpub account gap limit of 20, and PIVX's blockbook instances also share the same gap limit.

Will give this some testing and await ACKs of others to merge, however, could you fix the whitespace deletions? It's hard to review your PR with them, and we will resolve whitespace issues in #53 soon, and also edit the comment below the edited line, since it still states **10** rather than **20**.

**Review by Duddino — APPROVED** [review]
Thanks for this PR! It works fine, tested with [this](https://explorer.duddino.com/xpub/xpub6CVzXM7bjMc5nmFs8HbeMreCh6STspbunZ8UJ5RXPGfpsMyyXWeVRHhth7JsCZ5P4CUkzeSeYi75aLjYEgG14NBP6uwRQxVMDxo6e9dkeoU) account, and it does show the correct the balance even with the last possible address, but could you please remove the whitespace changes? That could cause some useless conflicts, and like JSKitty said we're going to resolve it in #53 anyways

**Review by JSKitty — CHANGES_REQUESTED** [review]
The whitespace / indenting changes of this PR are already having conflicts with Master branch, these **need** reverting, and the comment under your changed line to also be updated, then we're good to merge ASAP, these are only quick changes for you. :heavy_check_mark:

**Comment by Duddino** [comment]
Looks like you changed the other comment, however the spacing issues still remain

**Review by JSKitty — APPROVED** [review]
**tACK**, I have removed the whitespace, merged with Master, and also converted the "magic number" into a JSDoc'd constant.

Note: I don't know why you didn't remove the whitespace in 4 days :sweat_smile: but I'll let this one pass, please be more responsive and cooperative in future PRs, this uses up valuable time.

**Comment by panleone** [comment]
the code is ok... but before making a PR you should at least study how GIT work since you couldn't remove white spaces of your last commit

**Review by panleone — APPROVED** [review]
tACK

**Review by Duddino — APPROVED** [review]
tACK

**Comment by JSKitty** [comment]
🪙 **135 PIV** bounty fulfilled and sent

**Pull request merged**
