### PR TITLE
Add duddino explorer

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

Add my own explorer, https://explorer.duddino.com I've been hosting this since around December, and it's always been available. The explorer is logless and secure, plus the more the better

### CODE REVIEW

**Review by JSKitty — CHANGES_REQUESTED** [review]
Good 'ol CORS rules are preventing my client (latest [Fleek.co build](https://bafybeibaawoz2gp4tjn4ogdc54237j2j5iwj3q34m43w6znq4gurq75mha.on.fleek.co/)) from syncing:
```
Response body is not available to scripts (Reason: CORS Missing Allow Origin)
```

**Comment by Duddino** [comment]
My nginx was misconfigured; It should work now

**Review by JSKitty — APPROVED** [review]
**tACK** abb005b0e27e9a14a56e689f47573635a797c47b, perfect! Happy to further decentralise MPW :rocket:

**Comment by panleone** [comment]
thanks for the patch Duddino! I was going to find a good color this evening but this surely saved me some time :+1:

**Review by panleone — APPROVED** [review]
tACK abb005b0e27e9a14a56e689f47573635a797c47b
I usually use that explorer lol

**Pull request merged**
