### PR TITLE
[CI] ESLint + Prettier

### PR DESCRIPTION
**Pull request by JSKitty**
A PR created on behalf of @11Tuvork28's branch work :purple_heart: to standardise our codebase's style and enforce linting of PRs / merges via CI pipeline.

`// TODO: RFC and PR description, draft currently`

### CODE REVIEW

**Comment by Duddino** [comment]
I think we should also write a `style.md` for things that can't be enforced with a linter alone (for example variable type as a prefix)

**Comment by 11Tuvork28** [comment]
Also JDOC should be required before a PR is accepted imo

**Comment by JSKitty** [comment]
I think we should handle non-CI (e.g: [CONTRIBUTING.md](https://github.blog/2012-09-17-contributing-guidelines/)) in a separate PR, keeping this one simply for ESLint + Prettier integration (it's currently more important that we enforce code CI **before** any large additional PRs are created, otherwise we have one huge mess of conflicts to resolve)

**Comment by 11Tuvork28** [comment]
I created a patch [CI_FIX.patch](https://github.com/PIVX-Labs/MyPIVXWallet/files/10287932/CI_FIX.patch), its not everything but at least every I did so far. Fixes most errors and merges current master onto it

**Comment by JSKitty** [comment]
Nuking in favor of a new PR with a more gradual transition approach.

**Pull request closed without merging**
