### PR TITLE
[TEST] Network simulator and some initial tests

### PR DESCRIPTION
**Pull request by panleone**
## Abstract

The aim of this PR is improving the unit test coverage by adding a mock to the network class.

How to use it in unit tests:

1.  Mock the file `vi.mock('../../../scripts/network.js')`
2.  Create a bunch of wallets with the functions `setUpLegacyMainnetWallet()`. Those wallets have a non-zero balance and are synced.
3.  After creating txs with any wallet call `getNetwork().sendTransaction(txHex)`
4.  Once enough txs are added mint a new block with `getNetwork().mintBlock()`
5.  Trigger download of the block for all wallets in the test by calling the global.js function `refreshChainData();`

Notice that calling `refreshChainData()`  will emit a signal that is received by wallets as
```
 getEventEmitter().on('new-block', async (block) => {
            if (this.#isSynced) {
                await this.getLatestBlocks(block);
                getEventEmitter().emit('new-tx');
            }
        });
```
which makes tests reliable, in the sense that the normal sync flow is followed, with the only difference that instead of blockbook, blocks are provided by the mock class.

I have also added a couple of tests:

- Create a bunch of txs between a HD and a Legacy wallets and verify that txs are received and balance is updated as expected
- Verify that HD wallets are aware of at least `MAX_ACCOUNT_GAP` addresses after the last used

---

## Testing

Tests working as expected

### CODE REVIEW

**Comment by panleone** [comment]
new tests will fail until #363 is merged (which will solve the sync bug)

**Review by Duddino — COMMENTED** [review]
These looks good, my only nit is that these are no longer unit tests, so just move them in a different folder

**Comment by panleone** [comment]
> These looks good, my only nit is that these are no longer unit tests, so just move them in a different folder

done

**Review by Duddino — APPROVED** [review]
ACK nice tests

**Review by JSKitty — APPROVED** [review]
**tACK** 899e48aa9effebe8ed30f49d3249c63a63a2fd61

**Pull request merged**
