### PR TITLE
Network refactor

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

Refactored the network code to be Object oriented and not depend on UI/mempool code. This PR depends on #88 

## What does this PR address?
Network code was spaghetti-like, it depended on UI and mempool. In my opinion the network should not handle UI code.

## What features or improvements were added?
Instead of calling UI functions directly in the network, I added a global event system, and the network emits these events when something happens. Systems that depend on these callbacks can simply subscribe to these events.

### CODE REVIEW

**Comment by JSKitty** [comment]
This is a *really* interesting way of handling the netcode, but honestly I love the structure - I need some time to review this properly, but I'd definitely give it a "Concept **ACK**" with the direction it's heading.

Keeping UI control outside of "core" MPW components is good, it also allows us to modularise MPW better (i.e: turn parts of MPW in to headless libraries for external use, etc...).

Awesome job so far - the conflicts and massiveness of the PR will make it a difficult one. :yum:

**Review by Liquid369 — APPROVED** [review]
tACK 2b40e17c4a768c709a389fccec4631f0393987b6

I really like the way this is going as well. 
I will say I did notice a small decrease on the sync speed at this point in time, but now that we have a cleaner networking code, we can potentially identify those in subsequent PR's or it was just me with wayyy too many tabs open but cannot close them at this time.
I really do not have any nits, just seen some updates that I will utilize for the Masternode PR, like hiding the load more lol
It's hard to say I see any issues at the moment. 

Sync ✅ 
Rewards ✅ 
Delegations ✅ 
Transactions ✅

**Review by Liquid369 — APPROVED** [review]
tACK

**Review by panleone — APPROVED** [review]
tACK  889420f9c698cc4a3da975b1137285c3bee8f029

**Review by JSKitty — APPROVED** [review]
**tACK** 889420f9c698cc4a3da975b1137285c3bee8f029 - Much more organised and sane implementation of an aging system - no issues in my spam-testing of TX'es across multiple explorers and configurations!

Nice start to the decoupling of the UI from the internal "modules", code is also incredibly clean + documented. :tada:

**Pull request merged**
