### PR TITLE
Remove legacy encrypt Modal and functions

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

Encrypt modal was never deleted from `index.template.html`, resulting in some duplicate code.
Thank you @BreadJS for bringing this to my attention

## Testing
- Test that encrypt modal works as intended

### CODE REVIEW

**Review by JSKitty — CHANGES_REQUESTED** [review]
Encryption model upon first encryption looks good, however I noticed a pretty serious bug (potentially not related to the PR): the "Change Password" dialog, which uses the same UI elements, seems to be broken;

If you change your password, the new password you set (and the old one) cannot unlock the wallet, I'm assuming a string or input is getting lost somewhere, but this makes wallets potentially inaccessible.

**Comment by BreadJS** [comment]
> Encryption model upon first encryption looks good, however I noticed a pretty serious bug (potentially not related to the PR): the "Change Password" dialog, which uses the same UI elements, seems to be broken;
> 
> If you change your password, the new password you set (and the old one) cannot unlock the wallet, I'm assuming a string or input is getting lost somewhere, but this makes wallets potentially inaccessible.

That was the issues that I forgot to mention when talking to you on Discord about it @Duddino

**Comment by JSKitty** [comment]
Re-testing with #339 merged.

**Review by JSKitty — APPROVED** [review]
**tACK** 08d362295b8e848aa8db4e82bc8d9dd08bf791bb

Repeated the tests I ran back in #339, looking good, I did notice a very small text-only regression from the original Vue port (not related to PR), I'll patch it tomorrow likely.

**Pull request merged**
