### PR TITLE
Restore identicon to their former beauty

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

Fix identicons

## Testing

- Open MPW
- Stare in awe at the new identicons

master:
image
This PR:
image

### CODE REVIEW

**Review by JSKitty — COMMENTED** [review]
The squishy icon is definitely fixed, however, seems on mobile the actual itself actually shrinks quite small, looks a bit odd and inconsistent;

PR
image


Master
image

**Comment by Duddino** [comment]
Fixed

**Review by JSKitty — APPROVED** [review]
**tACK** ad1c7d1ed5e8f0074de673bb15624792f4946c41

**Review by panleone — APPROVED** [review]
tACK ad1c7d1ed5e8f0074de673bb15624792f4946c41

**Pull request merged**
