### PR TITLE
Ignore test directory in eslint

### PR DESCRIPTION
**Pull request by Duddino**
## Testing

Check that tests pass

### CODE REVIEW

**Review by panleone — DISMISSED** [review]
tACK 7fdf55643b36c652a557d96dc5f9648de4a2524c

**Review by JSKitty — CHANGES_REQUESTED** [review]
We should also ignore `dist`, since if you've previously built MPW, then the dist JS is linted, and you're presented with more errors than there is atoms in the universe.

**Review by JSKitty — APPROVED** [review]
**tACK** 8e819cd4aa951a19120649e621ba0385a3e01cb5

**Review by panleone — APPROVED** [review]
re-tACK 8e819cd4aa951a19120649e621ba0385a3e01cb5

**Pull request merged**
