### PR TITLE
v1.5.0 finalised

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

This PR concludes the interim update between v1.4.0 and v2.0, being the last update (barring major issues) prior to the v2.0 Interface Revamp and SHIELD UX redesign completion.

Minor CSS changes are the only changes in this PR, alongside the Version Bump and Changelog update.

---

## Testing
To test this PR, it's suggested to attempt these user flows, or variations of these:
- Test **Imports** and **New Wallet** generations.
- Test that Syncing works as expected, without errors, and that it resumes where it left off **IF** you restart MPW halfway through.
- Test **Sending and Receiving** both **Transparent** and **SHIELD** PIV.
- Test **Contacts**.
- Test **Staking and Unstaking**.
- Any other small, quick tests you feel like doing... do them!

If any errors are found, the PR works unexpectedly, or you have viable suggestions to improve the UX or functionality of the PR, let me know!

---

### CODE REVIEW

**Review by Liquid369 — COMMENTED** [review]
tACK 89470f1f5703c55e72f0f1dd610ca58b5437fd34

**Review by Duddino — APPROVED** [review]
tACK

**Review by Liquid369 — DISMISSED** [review]
tACK 89470f1f5703c55e72f0f1dd610ca58b5437fd34

**Review by Luke-Larsen — DISMISSED** [review]
tACK https://github.com/PIVX-Labs/MyPIVXWallet/commit/89470f1f5703c55e72f0f1dd610ca58b5437fd34

**Pull request merged**
