### PR TITLE
Docker image CI FIX

### PR DESCRIPTION
**Pull request by ZOZOTHEHellhound**
## Abstract

Fixes the issue #77, while also improving the image size. This leads to saving in bandwidth and also enables hosters like me to again autopull the image without it being to big without reason.

## What does this PR address?
Fixes failing CI auto builds

## What features or improvements were added?
Nothing but reduced image size.

## How does this benefit users?
Not the users but the ones hosting an instance, as image pulling bandwidth is reduced.

I don't want anything for it keep it, like we would have done all along.

In love
Zozo the hellhound <3

### CODE REVIEW

**Review by JSKitty — APPROVED** [review]
:tada: **tACK**, successfully ran the deployment on my [alt-repo](https://github.com/jskitty-repos/MyPIVXWallet/actions/runs/4057083880/jobs/6982394091).

This is appreciated, a reward is still on the table if you'd like, thank you for the help. :pray:

**Comment by JSKitty** [comment]
> do I really need to use this account from now on?

No need, you should have access again @11Tuvork28. :pray:

**Review by Liquid369 — APPROVED** [review]
tACK 798b8f7a1e616a0b41dcd9b765a170bcc7c0ee17

You beat me to it 🥇 
I was just chaining the command, thanks for the fix!

**Comment by JSKitty** [comment]
The Docker whale comes back to life.

# 🐋

Just waiting on @Duddino 's review and we'll merge it right in.

**Review by Duddino — APPROVED** [review]
tACK

**Comment by JSKitty** [comment]
Merging, reward proposal [here](https://forum.pivx.org/threads/lmp-docker-fix.1294/) and governance tracking [here](https://pivx.org/proposals).

**Pull request merged**
