### PR TITLE
Add support for testnet addresses starting with x 

### LINKED ISSUE #37: Add support for testnet addresses starting with x
Testnet addresses can start with `x` as well as `y`.
Should probably change [this](https://github.com/PIVX-Labs/MyPIVXWallet/blob/3589c18d6c54d499fc1be5c468d2f7066b505402/index.html#L77) to an array, and adapt the code accordingly

### PR DESCRIPTION
**Pull request by PeterL73**
## Issue being fixed #37
Destination addresses are validated with the first letter. 
## What was done
Destination validation was added
Vanity Wallet generation was refactored to automatically precede the user defined prefix with the network prefix
Support for x prefix in testnet addresses was added
## How Has This Been Tested
Successful transactions were made to destination addresses starting with x and y
Vanity Wallets where generated with the appropriate network prefix
## Noticeable Changes
New user workflow to generate Vanity Wallet

### CODE REVIEW

**Review by Duddino — APPROVED** [review]
tACK. Good work, my only nit is that you can't choose which prefix you want during vanity wallet creation, but since it only affects testnet it doesn't really matter.

**Review by JSKitty — APPROVED** [review]
**tACK**! Working as I'd expect, and VanityGen looks neat!

**Comment by Liquid369** [comment]
tACK as expected

**Comment by JSKitty** [comment]
:moneybag: :purple_heart: Bounty delivered to previously-provided address!

**Pull request merged**
