### PR TITLE
Fixed ledger not working

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract
Ledger wasn't working because of the library being updated (I think?) when switching to webpack

## What does this PR address?

Fix ledger

## What features or improvements were added?

Fix ledger

## How does this benefit users?

They can sue ledger

### CODE REVIEW

**Review by Liquid369 — APPROVED** [review]
utACK c4cff62a54a65c3ad4920de27849934d09458576
Meets standards of the documentation of the lib, I guess soon time to buy a ledger

**Review by JSKitty — CHANGES_REQUESTED** [review]
There's a few issues remaining, tested on Brave + Ledger Nano S;
- Ledger error codes aren't being translated in to English correctly.
- Many "String Templates" aren't being filled in the notifications.

image

image


But functionally, I'm able to derive new addresses perfectly fine, and verify them, all as usual.

**Review by JSKitty — APPROVED** [review]
**tACK**, basics, address imports + verification, and all notifications tested successfully.

**Review by Liquid369 — APPROVED** [review]
uTACK e2162c7887bd087a92ec8b4b77d90f6d4315bbd8

Looks good, soon to test with a ledger myself to help out more
Everything to specs based on the lib

**Review by panleone — APPROVED** [review]
tACK: tested with ledger emulator

**Pull request merged**
