### PR TITLE
[Trivial] Standardised functions

### PR DESCRIPTION
**Pull request by JSKitty**
A simple non-functionally-differing PR which standardises *most* top-level MPW functions in a format that IDEs can properly follow, and plus it's just easier to understand them by hand, too.

For example: VSCode, for me, would be unable to see many `wallet.js` functions while trying to apply them in other modules and files, this fixes those cases now, making development a tid bit faster, as I'm lazy.

### Note:
The **only** 'real' functional change is that these functions can now be overridden, but this is actually a benefit for debugging, and I would hope users aren't dumb enough to paste random commands into a debug console... thinking about it, we could make a PR to display a huge warning message in the console, anyway. :shrug:

### CODE REVIEW

**Comment by Duddino** [comment]
Could you add `"use strict";` on top of our scripts?

**Comment by JSKitty** [comment]
Added into all scripts that make sense currently; before bitTrx.js, I'd like to refactor that whole file to get rid of the weird function-import style, but should be safe for another PR to reduce complexity and conflicts.

**Review by Duddino — DISMISSED** [review]
wallet.js:346 should be removed, that was an old variable we since got rid of, and `use strict` causes it to throw an error.
Unrelated to the PR: wallet.js:352 should be `getNewAddress({updateGUI: true})`
Still approving because these are really minor changes

**Comment by JSKitty** [comment]
Corrected both issues, will need a re-ACK due to branch protection dismissal.

**Review by Duddino — APPROVED** [review]
tACK

**Review by Shangaman — APPROVED** [review]
tAck, nothing to say :)

**Pull request merged**
