### PR TITLE
New Landing (+ Loading Screen)

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

To prepare for the upcoming, redesigned, off-app Landing Page designed by Shorn, the in-app lander is being removed to allow for an external landing page to take it's place.

In place, is now a simple Loading Screen, which displays for as long as MPW's "start()" bootup takes, this gives us some nice flexibility to design a better loading system, while also de-coupling the App (MyPIVXWallet) from a landing page, and directing users of the app directly to the Dashboard, rather than unnecessary extra clicks.

Once this new landing page is live, and the DNS is switched, **MPW v1.0** is considered complete, and will be deployed live.

The plan:
- The App (this repo) will be served at `app.mypivxwallet.org`
- The Landing ([here](https://mpw-1d4f14.webflow.io/)) will be served at `mypivxwallet.org`

# External Landing Page
image

# Loading Screen
image

### CODE REVIEW

**Review by Duddino — APPROVED** [review]
Looks good, Just one nit: pressing the logo should open the "dashboard tab"

**Review by Duddino — APPROVED** [review]
tACK

**Review by Liquid369 — APPROVED** [review]
tACK f3fdd07026aee7d9ddef86b71305de66f45cb9dd

**Review by SKDTXL — APPROVED** [review]
tACK: f3fdd07026aee7d9ddef86b71305de66f45cb9dd
Looking good and smooth.

**Pull request merged**
