### PR TITLE
Status Icons Redesign

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

The old 'status' system for MPW looked extremely clunky, inconsistent, and used too much "screen space".

This PR redesigns MPW 'statuses' to be FontAwesome icon-based with descriptive Bootstrap Tooltips upon hover, all icons are clickable, some will totally hide when disabled (i.e: Debug Mode), and some will switch icon accordingly to their mode, like Internet Access.

**Production:**
image

**Pull Request:**
image

## What does this PR address?
This PR redesigns the Status system to an 'icon bar' with status icons and descriptive tooltips, massively reducing screen-space used, and giving full consistency to any existing and future MPW statuses that need to be displayed to the user.

## What features or improvements were added?
A redesigned Status Bar with icons and descriptive tooltips.

## How does this benefit users?
It's much nicer on the eyes, easy to understand, and uses far less screen real-estate, which helps draw the user's focus to where it's needed (the core app), only displaying verbose info upon hover.

### CODE REVIEW

**Review by Liquid369 — DISMISSED** [review]
tACK 459c15851c5093ec5582ffbabf7439f2984622de

With a minor nit
Screenshot 2023-03-07 at 9 38 06 AM
This icon does not correspond too much with 
Screenshot 2023-03-07 at 9 38 25 AM
This icon, so maybe we can make them the same for both

**Review by Liquid369 — APPROVED** [review]
Much better now!
tACK a5d34ec2af0df4864be851fb8a8bc45ce254da2b

**Review by Luke-Larsen — APPROVED** [review]
Works and looks great
tACK https://github.com/PIVX-Labs/MyPIVXWallet/commit/a5d34ec2af0df4864be851fb8a8bc45ce254da2b

**Review by Duddino — APPROVED** [review]
tACK

**Pull request merged**
