### PR TITLE
Performance and SEO optimisations

### PR DESCRIPTION
**Pull request by JSKitty**
## Abstract

To improve MPW's size and loading time, this PR employs a bunch of webpack-level and dependency changes, such as:
- Setting webpack to `production` mode (enables many dist optimisations) for builds.
- Plugging in a CSS minimizer.
- Replacing the bloaty whole `lodash` import for per-function [lodash-es](https://www.npmjs.com/package/lodash-es) imports.
- For SEO/Indexing purposes: switching the navbar `<a>` buttons to `<span>`.

Much of these issues were shown with the help of [Lighthouse](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fmypivxwallet.org%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa), in which MPW has quite bad performance and loading times - this PR will dramatically decrease the loading time for MPW.

My current local tests (using production and this PR) show these results:

**Production (CSS and JS only)**
image

**Pull Request (CSS and JS only)**
image

## What does this PR address?
The PR helps address the slow loading times of MPW, by vastly decreasing the app's compiled size and by stripping unused dependency bloat from the app.

## What features or improvements were added?
No user-level features, just faster loading! (Which also means less bandwidth usage).

## How does this benefit users?
MPW will now load significantly faster, especially notable on slower networks or hosts, this PR also improves SEO and search engine indexing by the boost in performance, and the tweak to the navbar which resolves some indexing issues.

### CODE REVIEW

**Review by BreadJS — APPROVED** [review]
I'm all for it! LGTM!

**Review by Liquid369 — APPROVED** [review]
tACK 6cfcff73410ec0a1205d1e56ff59c28a3eb2ee86
We absolutely need this the question is nonsensical in the perf increase alone and then SEO we do need to start addressing.
Great start

**Review by Duddino — CHANGES_REQUESTED** [review]
Can you commit package.lock.json as well?

Adding this to the config should prevent bn.js to get loaded multiple times
```js
resolve: {
  alias: {
    'bn.js': path.join(__dirname, 'node_modules/bn.js/lib/bn.js'),
  }
},
```

**Review by Duddino — DISMISSED** [review]
tACK, it's perfect now

**Review by Liquid369 — APPROVED** [review]
tACK 500ada30120a79a33f6b4bd002931cc0c0821214

Shoot, just saw, resolve conflicts lol

**Comment by JSKitty** [comment]
Resolved conflicts, good to go again.

**Review by Duddino — APPROVED** [review]
tACK

**Review by Liquid369 — APPROVED** [review]
tACK b3be63b226aaeeabbb34f466dc2133baf96d502a

**Pull request merged**
