### PR TITLE
Polyfill nodejs crypto with noble

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract

Quite a few of our libraries use the `crypto` module, which is only available on nodejs.
Prior to this PR we were using the `crypto-browserify`. However, in #47, we decided to use the `noble` library, which is considerably smaller.
This also paves the way to remove `bn.js` and our next biggest library `elliptic`, which is the only remaining library which depends on it in the main bundle (Ledger also depends on `bn.js`, but it's in a different bundle).
This cuts down the main bundle from 419KB to 386KB (Gzipped) 

## Testing
Test that the polyfill works as intended.
The affected libraries were: `pivx-promos`, `hdkey`, `base32`

### CODE REVIEW

**Review by panleone — CHANGES_REQUESTED** [review]
importing seed phrase does not work

**Review by panleone — DISMISSED** [review]
tACK

**Review by JSKitty — DISMISSED** [review]
**tACK** d47cbcb7d1b619442b8b1ebf47d744ffff22fa95

Tested as many wallet functions as I could: derivation of Legacy and HD, Shield and Transparent Txs, Promo Creation and Redemption, Staking and Unstaking - all is working well and the bundles reduced nicely!

**Review by panleone — APPROVED** [review]
re-tACK 9f8419ad1ecd5d06e7d9ec7065dc1c7fa6d93d57

**Pull request merged**
