### PR TITLE
Governance vue

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract
This PR ports the Governance and Masternode tab in vue, massively simplifing the render logic.

## TODO 
- [x] Wait for #372 to be merged
- [x] Create proposal
- [x] Figure out when to update to fetch updates from the RPC node
- [ ] Check mobile page
- [x] Clean up
- [x] Unit tests

## Testing 
- Check the entirety of the masternode page
- Check the entirety of governance page, including proposals

### CODE REVIEW

**Review by panleone — CHANGES_REQUESTED** [review]
quick feedback on the governance tab:

- Voting a proposal No/Yes when you don't have a masternode doesn't show any alerts
- Clicking the proposal address doesn't open the explorer

The rest looks good. Will test proposal and masternode creation soon

**Review by panleone — CHANGES_REQUESTED** [review]
masternode collateral creation seems to be reversed:

It tries to create the transaction when the wallet is locked (thus throwing the error cannot sign with a view only wallet)

It tries to setMasterkey when the wallet is already unlocked (hence throwing the error a spending key is already loaded)

**Comment by JSKitty** [comment]
Very minor design consistency change: the voting buttons are not the same size, "Yes" is smaller than "No".

Prod:
image

PR:
image

**Review by panleone — CHANGES_REQUESTED** [review]
When creating the 10kPIVs masternode tx, the tab "Your Masternode Private Key..." doesnt get closed when pressing the X

**Review by panleone — CHANGES_REQUESTED** [review]
When opening MPW getProposals throw errors
```
mpw.js:sourcemap:104538 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at Masternode.getProposals (mpw.js:sourcemap:104538:41)
    at async fetchProposals (mpw.js:sourcemap:67700:26)
```

**Review by JSKitty — APPROVED** [review]
**tACK** 215a3b170a41b31498029453c4622b5995fb3c62

We'll revisit the mobile + iOS bugs prior to v2.1 release.

**Review by panleone — APPROVED** [review]
tACK 215a3b170a41b31498029453c4622b5995fb3c62

**Pull request merged**
