### PR TITLE
View only mode

### LINKED ISSUE #51: Add wallet locking support + view only keys
You should be able to import xpub and public keys and be able to see the balance (when #49 is merged, vote on proposals if you have a masternode), as well as locking the wallet with a password

### PR DESCRIPTION
**Pull request by Duddino**
Closes #51.
Adds the ability to import addresses (and xpubs), delete private keys from your wallet and re-importing them if they were encrypted with a password (i.e. locking the wallet).
If you had previously encrypted the wallet, you will access MPW in view only mode, able to unlock or lock the wallet at any time.

Important:
I changed `deriveAddress` to be easier to understand and to have better support for compressed public keys. Please test that the addresses are generated correctly, because if they're not, there could be loss of funds. Using a tool like [this](https://iancoleman.io/bip39/) could help.

### CODE REVIEW

**Comment by JSKitty** [comment]
There's a key derivation conflict to resolve, however I'll get to testing and reviewing this ASAP. :rocket:

**Review by panleone — CHANGES_REQUESTED** [review]
code looks good... add the view only mode error handling in the function  
async function createMasternode() {...} 
as you did in other transactions.

Maybe you can add a "session" password to the locking system so the user can unlock without having to reimport the wallet (with "session" I mean that if the users reimport the wallet anyways he will find the wallet unlocked and can set a new password for view only mode)

**Review by JSKitty — APPROVED** [review]
**tACK**

I like the way the PR handles locking/unlocking, quite similar to the Core Wallet and I think in this case that's good, a session password to me seems 'too much' in regards to just being able to see your public keys / balances without unlocking.

I've added a few fixes and the MN creation check, finished JSDocs, done a bunch of mainnet testing over 100+ derived keys (Both while Locked and Unlocked at random), all seems good, tested with both Legacy and xpriv/seed wallets.

**Review by panleone — APPROVED** [review]
tACK

**Pull request merged**
