### PR TITLE
Add faster shield sync

### PR DESCRIPTION
**Pull request by Duddino**
## Abstract
Add faster shield sync.
This needs pivx shield and PivxNodeController updates

## Testing
- Sync shield wallets and assert that it is faster

### CODE REVIEW

**Review by panleone — DISMISSED** [review]
tACK f8d45ee42e8a065854afa65214c6d4d03c7f0e43

**Review by Liquid369 — DISMISSED** [review]
tACK f8d45ee42e8a065854afa65214c6d4d03c7f0e43
LGTM

**Review by Liquid369 — APPROVED** [review]
tACK 2bdd9375e7e3615dea381cde915d90569475be98

**Review by JSKitty — APPROVED** [review]
**tACK** 2bdd9375e7e3615dea381cde915d90569475be98

Synced, resynced, quit-halfway-and-continued, etc, various times. Looking good!

**Pull request merged**
