### PR TITLE
New 'Transfer' design and small other changes

### PR DESCRIPTION
**Pull request by BreadJS**
## Abstract
I've changed the design of the sending page to make it more responsive, and have a cleaner UI. 

## What does this PR address?
MPW was not really responsive for other devices and lacks a good design (IMO). My intend is to redesign MPW for a better look and also make it as responsive as possible for every device.

## What features or improvements were added?
1. New `Transfer`
    - Menu animates from bottom to top when clicking on the `Withdraw` button
    - Simple design (removed the advanced features for now, they will be add back in a future PR)
    - Removed `Send` menu from navigation bar
2. Other changes
    - Removing dotted outline on textboxes
    - Changed `Dashboard` height to remove empty space
    - Added an extra medium size button

## How does this benefit users?
A better design will lure more users in using MPW. This also applies for making the site more responsive.

## PIVX Address
`DQnmBB6b6xLdjt2kqfgDWJGZGoMSATp1xS`

### CODE REVIEW

**Review by Duddino — COMMENTED** [review]
The "Transaction sent" alert only lasts for a very short amount of time, can you increase that?
Other than that I really like how the PR is progressing

**Review by JSKitty — APPROVED** [review]
**tACK** - Brilliant design upgrade, **HUGE** enhancement to MPW usability, and starting from this PR, I believe it's now safe to consider MPW as "bare minimum READY" for mobile.

Let the mobile race begin. :rocket:

**Review by Liquid369 — DISMISSED** [review]
tACK bb5bc50ed8bf9d6e34821f445f1b96cd4d459b14
To those following and concerned, the export private key is working here, so will be functional after merging
LGTM!

**Review by Liquid369 — APPROVED** [review]

**Comment by Liquid369** [comment]
tACK

**Review by JSKitty — APPROVED** [review]
Final **tACK** via testnet.

**Pull request merged**
